import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";
import { spacing } from "../theme/spacing";

export const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xl,
  },
  container: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xl,
  },
  cloudOne: {
    position: "absolute",
    top: 34,
    right: 30,
    width: 150,
    height: 84,
  },
  cloudTwo: {
    position: "absolute",
    top: 92,
    left: 18,
    width: 120,
    height: 70,
  },
  cloudBase: {
    position: "absolute",
    left: 18,
    bottom: 10,
    width: 118,
    height: 38,
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 999,
  },
  cloudBumpLarge: {
    position: "absolute",
    left: 30,
    bottom: 30,
    width: 48,
    height: 42,
    backgroundColor: "rgba(255,255,255,0.88)",
    borderRadius: 999,
  },
  cloudBumpMid: {
    position: "absolute",
    left: 66,
    bottom: 28,
    width: 46,
    height: 40,
    backgroundColor: "rgba(255,255,255,0.88)",
    borderRadius: 999,
  },
  cloudBumpSmall: {
    position: "absolute",
    left: 10,
    bottom: 22,
    width: 38,
    height: 34,
    backgroundColor: "rgba(255,255,255,0.82)",
    borderRadius: 999,
  },
  cloudBaseSmall: {
    position: "absolute",
    left: 10,
    bottom: 8,
    width: 95,
    height: 30,
    backgroundColor: "rgba(255,255,255,0.75)",
    borderRadius: 999,
  },
  cloudBumpMidSmall: {
    position: "absolute",
    left: 26,
    bottom: 22,
    width: 40,
    height: 34,
    backgroundColor: "rgba(255,255,255,0.8)",
    borderRadius: 999,
  },
  cloudBumpTiny: {
    position: "absolute",
    left: 58,
    bottom: 20,
    width: 30,
    height: 26,
    backgroundColor: "rgba(255,255,255,0.78)",
    borderRadius: 999,
  },
  navbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
    marginTop: spacing.md,
  },
  navTitle: {
    color: colors.textPrimary,
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  navSubtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: "500",
    marginTop: 4,
    letterSpacing: 0.2,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.94)",
    borderWidth: 1,
    borderColor: "#C8DDF2",
    shadowColor: "#3B78AB",
    shadowOpacity: 0.09,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  logoutText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  navActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  navIconButton: {
    width: 42,
    height: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#C8DDF2",
    backgroundColor: "rgba(255,255,255,0.86)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#3B78AB",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 10,
    elevation: 1,
  },
  content: {
    gap: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: 112,
  },
  card: {
    borderWidth: 1,
    borderColor: "#D4E6F5",
    borderRadius: 24,
    padding: spacing.lg,
    backgroundColor: "#FCFEFF",
    gap: spacing.xs,
    shadowColor: "#3A76A8",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 12,
    elevation: 1,
  },
  statusRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  statusPill: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#D1E5F6",
    borderRadius: 18,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    backgroundColor: "rgba(255,255,255,0.8)",
    gap: 4,
  },
  statusPillLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  statusPillValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "700",
  },
  chartCard: {
    borderWidth: 1,
    borderColor: "#D1E5F5",
    borderRadius: 24,
    padding: spacing.lg,
    backgroundColor: "#FCFEFF",
    gap: spacing.xs,
    shadowColor: "#3A76A8",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 12,
    elevation: 1,
  },
  rangeRow: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  rangeChip: {
    borderWidth: 1,
    borderColor: "#D3E6F6",
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.78)",
  },
  rangeChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  rangeChipText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
  rangeChipTextActive: {
    color: "#FFFFFF",
  },
  labelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: spacing.xs,
    paddingHorizontal: 2,
  },
  axisLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  axisLabelActive: {
    color: colors.accent,
    fontWeight: "700",
  },
  chartHint: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  chartPlayPanel: {
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: "#D4E6F4",
    borderRadius: 12,
    backgroundColor: "#FCFEFF",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: 2,
  },
  chartPlayLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  chartPlayValue: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "800",
  },
  chartPlayTrend: {
    fontSize: 12,
    fontWeight: "700",
  },
  chartTrendCalmer: {
    color: "#1D6D45",
  },
  chartTrendHigher: {
    color: "#A04747",
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "700",
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  sectionTitleIcon: {
    width: 24,
    height: 24,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(47,120,198,0.11)",
    borderWidth: 1,
    borderColor: "rgba(47,120,198,0.16)",
  },
  softText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  messageCard: {
    borderWidth: 1,
    borderColor: "#D1E4F4",
    borderRadius: 26,
    padding: spacing.lg,
    backgroundColor: "#FCFEFF",
    gap: spacing.sm,
    shadowColor: "#3A76A8",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 12,
    elevation: 1,
  },
  messageTitle: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  messageHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  messageIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0F7FF",
    borderWidth: 1,
    borderColor: "#D6E7F7",
  },
  messageText: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 27,
  },
  reframeCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DBE9F5",
    backgroundColor: "#FCFEFF",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
  },
  reframeTitle: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  reframeSteps: {
    gap: spacing.xs,
  },
  reframeHint: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 21,
  },
  recommendCard: {
    borderWidth: 1,
    borderColor: "#D0E5F6",
    borderRadius: 24,
    padding: spacing.lg,
    backgroundColor: "#FCFEFF",
    gap: spacing.xs,
    shadowColor: "#3A76A8",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 12,
    elevation: 1,
  },
  noteInQueueTitle: {
    marginTop: spacing.sm,
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  noteSparkRow: {
    marginTop: spacing.xs,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    justifyContent: "space-between",
  },
  noteSparkCard: {
    width: "48%",
    aspectRatio: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CFE3F5",
    backgroundColor: "#F7FBFF",
    padding: spacing.sm,
    gap: spacing.xs,
  },
  noteSparkHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  noteSparkDate: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  noteSparkText: {
    color: colors.textPrimary,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  noteSparkPlaceholder: {
    width: "100%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D4E6F6",
    backgroundColor: "#F8FCFF",
    padding: spacing.sm,
  },
  noteSparkPlaceholderText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  trackRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#E5F1FC",
    paddingTop: spacing.sm,
  },
  nowPlayingHero: {
    marginTop: spacing.xs,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "#D9EAF7",
    borderRadius: 18,
    backgroundColor: "#FCFEFF",
    padding: spacing.md,
  },
  nowPlayingSquare: {
    width: 80,
    height: 80,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D8E8F7",
    backgroundColor: "#F3F8FE",
    alignItems: "center",
    justifyContent: "center",
  },
  nowPlayingMeta: {
    flex: 1,
    gap: 4,
  },
  nowPlayingLabel: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  albumCarouselTitle: {
    marginTop: spacing.sm,
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  albumCarousel: {
    paddingTop: spacing.xs,
    paddingBottom: 2,
    gap: spacing.sm,
  },
  albumCard: {
    width: 138,
    height: 252,
    borderWidth: 1,
    borderColor: "#D8E8F7",
    borderRadius: 16,
    backgroundColor: "#FCFEFF",
    padding: spacing.sm,
    gap: spacing.xs,
    overflow: "hidden",
  },
  albumInfoTap: {
    gap: spacing.xs,
  },
  albumCardActive: {
    borderColor: "#8DBCE7",
    backgroundColor: "#F3F9FF",
  },
  albumCover: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D7E8F7",
    backgroundColor: "#F1F8FF",
    alignItems: "center",
    justifyContent: "center",
  },
  albumCoverAlt: {
    backgroundColor: "#F0F8FF",
  },
  albumTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  albumSub: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  albumAction: {
    marginTop: "auto",
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "#D4E7F7",
    borderRadius: 999,
    backgroundColor: "#F2F8FF",
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
  },
  albumActionText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: "700",
  },
  trackMetaMini: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  trackName: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: "600",
  },
  trackLeftWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  trackIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#C6DEF3",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F2F8FF",
  },
  trackSub: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  trackDuration: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  playChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    borderWidth: 2,
    borderColor: "#D0E4F6",
    backgroundColor: "#F2F8FF",
    borderRadius: 999,
    paddingHorizontal: spacing.xs,
    paddingVertical: 5,

  },
  playChipText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: "700",
  },
  legendCompactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: spacing.xs,
  },
  legendDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  legendCompactText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  listItem: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 22,
  },
  anchorRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  anchorChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#D7E8F7",
    backgroundColor: "#FCFEFF",
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
  },
  anchorChipText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
  journalInput: {
    borderWidth: 1,
    borderColor: "#D5E7F6",
    borderRadius: 16,
    minHeight: 144,
    textAlignVertical: "top",
    padding: spacing.md,
    color: colors.textPrimary,
    backgroundColor: "#FCFEFF",
    fontSize: 16,
  },
  saveButton: {
    alignSelf: "flex-end",
    borderRadius: 12,
    backgroundColor: colors.accent,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginTop: spacing.xs,
    shadowColor: "#2D6AA0",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 7 },
    shadowRadius: 10,
    elevation: 3,
  },
  journalActionsRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  cancelEditButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#C6DDF2",
    backgroundColor: "#F3FAFF",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  cancelEditText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  savedNotesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  savedNoteCard: {
    width: "48%",
    minHeight: 196,
    maxHeight: 196,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D9E9F7",
    backgroundColor: "#FCFEFF",
    padding: spacing.sm,
    gap: spacing.xs,
    overflow: "hidden",
  },
  savedNoteHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  savedNoteBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#C6DEF3",
    backgroundColor: "#E9F4FF",
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  savedNoteBadgeText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  savedNoteDate: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  savedNoteText: {
    color: colors.textPrimary,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  noteActionRow: {
    flexDirection: "row",
    gap: spacing.xs,
    marginTop: "auto",
  },
  noteIconAction: {
    width: 30,
    height: 30,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#C8DFF3",
    backgroundColor: "#EDF6FF",
    marginRight: 2,
  },
  noteDeleteIconAction: {
    backgroundColor: "#FFF2F2",
    borderColor: "#F4D3D3",
  },
  emptySavedNotesText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: "600",
    marginTop: spacing.xs,
  },
  profileHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  profileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#BFD8F0",
    backgroundColor: "#EAF5FF",
    alignItems: "center",
    justifyContent: "center",
  },
  profileHeaderMeta: {
    flex: 1,
    gap: 2,
  },
  profileHeaderName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "700",
  },
  settingsFieldGroup: {
    gap: 6,
    marginTop: spacing.sm,
  },
  settingsLabel: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  settingsInput: {
    borderWidth: 1,
    borderColor: "#C5DDF2",
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.textPrimary,
    backgroundColor: "#FCFEFF",
    fontSize: 15,
    fontWeight: "500",
  },
  unitRow: {
    flexDirection: "row",
    gap: spacing.xs,
    marginTop: 2,
  },
  unitChip: {
    borderWidth: 1,
    borderColor: "#C7DEF3",
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: 7,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  unitChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  unitChipText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
  unitChipTextActive: {
    color: "#FFFFFF",
  },
  settingsValue: {
    borderWidth: 1,
    borderColor: "#D2E6F6",
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.textPrimary,
    backgroundColor: "#FCFEFF",
    fontSize: 15,
    fontWeight: "600",
  },
  datePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "#C7DEF3",
    borderRadius: 10,
    backgroundColor: "#FCFEFF",
    paddingHorizontal: spacing.sm,
    paddingVertical: 9,
  },
  datePickerButtonText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  settingsActionButton: {
    alignSelf: "flex-start",
    marginTop: spacing.sm,
    borderRadius: 12,
    backgroundColor: colors.accent,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    shadowColor: "#2D6AA0",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 7 },
    shadowRadius: 10,
    elevation: 3,
  },
  bottomBar: {
    position: "absolute",
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.md,
    backgroundColor: "rgba(255,255,255,0.88)",
    borderWidth: 1,
    borderColor: "#D0E4F5",
    borderRadius: 22,
    paddingVertical: 10,
    paddingHorizontal: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    shadowColor: "#3173A7",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 13,
    elevation: 3,
  },
  bottomItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    paddingVertical: 10,
    gap: 2,
  },
  bottomItemActive: {
    backgroundColor: "#E5F2FF",
  },
  bottomIcon: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "700",
  },
  bottomLabel: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 32, 52, 0.45)",
    justifyContent: "center",
    padding: spacing.lg,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    gap: spacing.md,
    maxHeight: "92%",
  },
  promptModalCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  modalScrollView: {
    maxHeight: 520,
  },
  modalScrollContent: {
    gap: spacing.sm,
    paddingBottom: spacing.xs,
  },
  questionnaireSectionCard: {
    borderWidth: 1,
    borderColor: "#D3E7F7",
    borderRadius: 14,
    backgroundColor: "#F8FCFF",
    padding: spacing.sm,
    gap: spacing.xs,
  },
  questionnaireSectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  questionnaireHelperText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
  },
  questionnaireSummaryCard: {
    marginTop: spacing.xs,
    borderWidth: 1,
    borderColor: "#C8DEF2",
    borderRadius: 12,
    backgroundColor: "#EDF6FF",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: 2,
  },
  questionnaireSummaryText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  questionnaireSummaryHint: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  questionnaireInput: {
    borderWidth: 1,
    borderColor: "#C5DDF2",
    borderRadius: 10,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.textPrimary,
    backgroundColor: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  questionnaireTextArea: {
    borderWidth: 1,
    borderColor: "#C5DDF2",
    borderRadius: 12,
    minHeight: 96,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.textPrimary,
    backgroundColor: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "700",
  },
  modalSubtitle: {
    color: colors.textSecondary,
    fontSize: 16,
    lineHeight: 24,
  },
  questionBlock: {
    gap: spacing.xs,
  },
  questionText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  optionRow: {
    flexDirection: "row",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  optionChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    backgroundColor: "#F4F9FF",
  },
  optionChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  optionText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  optionTextActive: {
    color: "#FFFFFF",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.sm,
  },
  secondaryAction: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: "#F4F9FF",
  },
  secondaryActionText: {
    color: colors.textPrimary,
    fontWeight: "600",
  },
  primaryAction: {
    borderRadius: 10,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: colors.accent,
  },
  primaryActionText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
});
